#docker-compose build
#docker-compose up

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: authservice
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authservice
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  sso:
    build:
      context: .
      dockerfile: build/sso/Dockerfile
    container_name: auth-sso
    depends_on:
      - postgres
    environment:
      CONFIG_PATH: /app/config/config_local.yaml
    ports:
      - "44044:44044"
    restart: unless-stopped

  migrator:
    build:
      context: .
      dockerfile: build/migrator/Dockerfile
    container_name: auth-migrator
    depends_on:
      - postgres
    environment:
      CONFIG_PATH: /app/config/config_local.yaml
    # Run once and exit; no ports exposed
    entrypoint: ["/app/migrator", "--once"]
    restart: "no"

volumes:
  postgres_data:

