version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: authservice
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authservice
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
