env: "local"
postgres:
  host: "postgres"
  port: 5432
  user: "authservice"
  password: "1234"
  dbname: "authservice"
  sslmode: "disable"
migrations_path: "migrations"
grpc:
  port: 44044
  timeout: 10h